siteTitle = 'Món Ngon 3 miền'
siteDescr = 'Sưu tầm ẩm thực'
siteDescription = "Tổng hợp những món đồ mà mình cần trong cuộc sống và công việc để khi đủ tiền thì rinh món đồ đó về nhà"
siteUrl = "https://AirBubble.info"
siteBandcampUrl = 'https://AirBubble.info'
siteMenuOne = 'Bữa Ăn'
siteMenuTwo = 'Món Ngon'
siteMenuThree = 'Quan tâm'
siteAddress = ''
siteAddress2 = 'Welcome to Món Ngon 3 miền'
sitePhone = '0902683189'
sitePhoneLink = 'tel:+84-090-268-3189'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
